### ISSUE TITLE
Distinguish between custom and built-on provider

### ISSUE THREAD

**Issue by hellboy81** [magnus-eriksson/oauth2-simple-client#1]
Please provide more info

**Comment by magnus-eriksson** [comment]
I'm not really sure about what you mean by "Distinguish between custom and built-on provider"?

Regarding providers and other usages (from the readme): 
_"The "provider" parameter can be any of the built in providers in "league/oauth2-client". You can head over to that repository to get more information. This package is using the latest 0.9.*-version. It can also be the name of a custom provider, more about those, go to the "league/oauth2-client". If it is a custom provider, enter the full namespace to that class, like: "provider" : "Namespace\To\Provider\MyProvider"_

This package is just a wrapper for the `league/oauth2-client` package. Providers are simply passed on to that package and anything regarding that, you need to check their documentation. 

You can always get the actual provider instance, using: `$leaguesProvider = $provider->getProvider();`

_**Note:** This package is using the 0.x version of their package, which now is on version 2.1, so this wrapper is a bit outdated. I might do an update when I find the time._

**Comment by hellboy81** [comment]
I have created my own wrapper base on yours

**Comment by magnus-eriksson** [comment]
Ok, cool! I recommend checking out the main package at [`league/oauth2-client`](https://github.com/thephpleague/oauth2-client) for info about the actual implementation. This wrapper doesn't care what the provider is, as long as it implements the Provider interface, since it doesn't really affects the purpose of it.
